// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA362ilIYX9-UGb4dWiqnMvPNRha1t7RIk',
    appId: '1:767909201554:web:8badd66ad864fe222ec84b',
    messagingSenderId: '767909201554',
    projectId: 'jasperfernandez-firebase',
    authDomain: 'jasperfernandez-firebase.firebaseapp.com',
    storageBucket: 'jasperfernandez-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1vZgxMlsJQKGrtFvqJXdCFes00aWZ5w',
    appId: '1:767909201554:android:f54ca44abdc7490b2ec84b',
    messagingSenderId: '767909201554',
    projectId: 'jasperfernandez-firebase',
    storageBucket: 'jasperfernandez-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOiW7KZneDnnGeTP85PCLRAtxVMZzPsoI',
    appId: '1:767909201554:ios:406baf8f7c7441cf2ec84b',
    messagingSenderId: '767909201554',
    projectId: 'jasperfernandez-firebase',
    storageBucket: 'jasperfernandez-firebase.appspot.com',
    androidClientId: '767909201554-ud4pj41b43jd2aahvlm0qi5ndrapf9le.apps.googleusercontent.com',
    iosClientId: '767909201554-e9u398caok0st630d830kh7b5figh3mu.apps.googleusercontent.com',
    iosBundleId: 'com.jasperfernandez.uminom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOiW7KZneDnnGeTP85PCLRAtxVMZzPsoI',
    appId: '1:767909201554:ios:406baf8f7c7441cf2ec84b',
    messagingSenderId: '767909201554',
    projectId: 'jasperfernandez-firebase',
    storageBucket: 'jasperfernandez-firebase.appspot.com',
    androidClientId: '767909201554-ud4pj41b43jd2aahvlm0qi5ndrapf9le.apps.googleusercontent.com',
    iosClientId: '767909201554-e9u398caok0st630d830kh7b5figh3mu.apps.googleusercontent.com',
    iosBundleId: 'com.jasperfernandez.uminom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA362ilIYX9-UGb4dWiqnMvPNRha1t7RIk',
    appId: '1:767909201554:web:270093654297f9ca2ec84b',
    messagingSenderId: '767909201554',
    projectId: 'jasperfernandez-firebase',
    authDomain: 'jasperfernandez-firebase.firebaseapp.com',
    storageBucket: 'jasperfernandez-firebase.appspot.com',
  );
}
